-- One-off repair of date-only columns saved at LOCAL midnight while the app ran on a UTC+1/+2 PC
-- (22:00 or 23:00 UTC of the previous day). Those values read one day early and re-save as a
-- spurious change in the audit log. Shift them to UTC midnight of the intended day. Only rows
-- at exactly 22:00:00 / 23:00:00 are touched; real timestamps and already-correct rows are not.

UPDATE "Salary" SET "effectiveFrom" = date_trunc('day', "effectiveFrom" + interval '2 hours') WHERE "effectiveFrom" IS NOT NULL AND EXTRACT(HOUR FROM "effectiveFrom") IN (22, 23) AND EXTRACT(MINUTE FROM "effectiveFrom") = 0 AND EXTRACT(SECOND FROM "effectiveFrom") = 0;
UPDATE "ExchangeRate" SET "effectiveFrom" = date_trunc('day', "effectiveFrom" + interval '2 hours') WHERE "effectiveFrom" IS NOT NULL AND EXTRACT(HOUR FROM "effectiveFrom") IN (22, 23) AND EXTRACT(MINUTE FROM "effectiveFrom") = 0 AND EXTRACT(SECOND FROM "effectiveFrom") = 0;
UPDATE "Employment" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "Employment" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
UPDATE "Project" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "Project" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
UPDATE "Project" SET "uatAcceptedDate" = date_trunc('day', "uatAcceptedDate" + interval '2 hours') WHERE "uatAcceptedDate" IS NOT NULL AND EXTRACT(HOUR FROM "uatAcceptedDate") IN (22, 23) AND EXTRACT(MINUTE FROM "uatAcceptedDate") = 0 AND EXTRACT(SECOND FROM "uatAcceptedDate") = 0;
UPDATE "Milestone" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "Milestone" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
UPDATE "Assignment" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "Assignment" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
-- Unique on (assignmentId, taskId, weekStartDate): skip a row whose corrected week already exists.
UPDATE "AssignmentPlan" a SET "weekStartDate" = date_trunc('day', a."weekStartDate" + interval '2 hours')
WHERE a."weekStartDate" IS NOT NULL AND EXTRACT(HOUR FROM a."weekStartDate") IN (22, 23) AND EXTRACT(MINUTE FROM a."weekStartDate") = 0 AND EXTRACT(SECOND FROM a."weekStartDate") = 0
  AND NOT EXISTS (SELECT 1 FROM "AssignmentPlan" b WHERE b."assignmentId" = a."assignmentId" AND b."taskId" IS NOT DISTINCT FROM a."taskId" AND b."weekStartDate" = date_trunc('day', a."weekStartDate" + interval '2 hours'));
UPDATE "Task" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "Task" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "TimeCard" SET "weekStartDate" = date_trunc('day', "weekStartDate" + interval '2 hours') WHERE "weekStartDate" IS NOT NULL AND EXTRACT(HOUR FROM "weekStartDate") IN (22, 23) AND EXTRACT(MINUTE FROM "weekStartDate") = 0 AND EXTRACT(SECOND FROM "weekStartDate") = 0;
-- Unique on (timeCardId, taskId, date): skip a row whose corrected day already exists on the card.
UPDATE "TimeEntry" a SET "date" = date_trunc('day', a."date" + interval '2 hours')
WHERE a."date" IS NOT NULL AND EXTRACT(HOUR FROM a."date") IN (22, 23) AND EXTRACT(MINUTE FROM a."date") = 0 AND EXTRACT(SECOND FROM a."date") = 0
  AND NOT EXISTS (SELECT 1 FROM "TimeEntry" b WHERE b."timeCardId" = a."timeCardId" AND b."taskId" IS NOT DISTINCT FROM a."taskId" AND b."date" = date_trunc('day', a."date" + interval '2 hours'));
UPDATE "LeaveRequest" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "LeaveRequest" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
UPDATE "LeaveReturn" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "LeaveReturn" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
UPDATE "Invoice" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "Invoice" SET "recognitionDate" = date_trunc('day', "recognitionDate" + interval '2 hours') WHERE "recognitionDate" IS NOT NULL AND EXTRACT(HOUR FROM "recognitionDate") IN (22, 23) AND EXTRACT(MINUTE FROM "recognitionDate") = 0 AND EXTRACT(SECOND FROM "recognitionDate") = 0;
UPDATE "Invoice" SET "periodStart" = date_trunc('day', "periodStart" + interval '2 hours') WHERE "periodStart" IS NOT NULL AND EXTRACT(HOUR FROM "periodStart") IN (22, 23) AND EXTRACT(MINUTE FROM "periodStart") = 0 AND EXTRACT(SECOND FROM "periodStart") = 0;
UPDATE "Invoice" SET "periodEnd" = date_trunc('day', "periodEnd" + interval '2 hours') WHERE "periodEnd" IS NOT NULL AND EXTRACT(HOUR FROM "periodEnd") IN (22, 23) AND EXTRACT(MINUTE FROM "periodEnd") = 0 AND EXTRACT(SECOND FROM "periodEnd") = 0;
UPDATE "InvoicePayment" SET "date" = date_trunc('day', "date" + interval '2 hours') WHERE "date" IS NOT NULL AND EXTRACT(HOUR FROM "date") IN (22, 23) AND EXTRACT(MINUTE FROM "date") = 0 AND EXTRACT(SECOND FROM "date") = 0;
UPDATE "Expense" SET "date" = date_trunc('day', "date" + interval '2 hours') WHERE "date" IS NOT NULL AND EXTRACT(HOUR FROM "date") IN (22, 23) AND EXTRACT(MINUTE FROM "date") = 0 AND EXTRACT(SECOND FROM "date") = 0;
UPDATE "Opportunity" SET "expectedCloseDate" = date_trunc('day', "expectedCloseDate" + interval '2 hours') WHERE "expectedCloseDate" IS NOT NULL AND EXTRACT(HOUR FROM "expectedCloseDate") IN (22, 23) AND EXTRACT(MINUTE FROM "expectedCloseDate") = 0 AND EXTRACT(SECOND FROM "expectedCloseDate") = 0;
UPDATE "Opportunity" SET "sowSignedDate" = date_trunc('day', "sowSignedDate" + interval '2 hours') WHERE "sowSignedDate" IS NOT NULL AND EXTRACT(HOUR FROM "sowSignedDate") IN (22, 23) AND EXTRACT(MINUTE FROM "sowSignedDate") = 0 AND EXTRACT(SECOND FROM "sowSignedDate") = 0;
UPDATE "Opportunity" SET "poDate" = date_trunc('day', "poDate" + interval '2 hours') WHERE "poDate" IS NOT NULL AND EXTRACT(HOUR FROM "poDate") IN (22, 23) AND EXTRACT(MINUTE FROM "poDate") = 0 AND EXTRACT(SECOND FROM "poDate") = 0;
UPDATE "Opportunity" SET "poValidUntil" = date_trunc('day', "poValidUntil" + interval '2 hours') WHERE "poValidUntil" IS NOT NULL AND EXTRACT(HOUR FROM "poValidUntil") IN (22, 23) AND EXTRACT(MINUTE FROM "poValidUntil") = 0 AND EXTRACT(SECOND FROM "poValidUntil") = 0;
UPDATE "OpportunityAmendment" SET "signedDate" = date_trunc('day', "signedDate" + interval '2 hours') WHERE "signedDate" IS NOT NULL AND EXTRACT(HOUR FROM "signedDate") IN (22, 23) AND EXTRACT(MINUTE FROM "signedDate") = 0 AND EXTRACT(SECOND FROM "signedDate") = 0;
UPDATE "VendorPayment" SET "invoiceDate" = date_trunc('day', "invoiceDate" + interval '2 hours') WHERE "invoiceDate" IS NOT NULL AND EXTRACT(HOUR FROM "invoiceDate") IN (22, 23) AND EXTRACT(MINUTE FROM "invoiceDate") = 0 AND EXTRACT(SECOND FROM "invoiceDate") = 0;
UPDATE "VendorPayment" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "VendorPayment" SET "paymentDate" = date_trunc('day', "paymentDate" + interval '2 hours') WHERE "paymentDate" IS NOT NULL AND EXTRACT(HOUR FROM "paymentDate") IN (22, 23) AND EXTRACT(MINUTE FROM "paymentDate") = 0 AND EXTRACT(SECOND FROM "paymentDate") = 0;
UPDATE "TaxPayment" SET "periodStart" = date_trunc('day', "periodStart" + interval '2 hours') WHERE "periodStart" IS NOT NULL AND EXTRACT(HOUR FROM "periodStart") IN (22, 23) AND EXTRACT(MINUTE FROM "periodStart") = 0 AND EXTRACT(SECOND FROM "periodStart") = 0;
UPDATE "TaxPayment" SET "periodEnd" = date_trunc('day', "periodEnd" + interval '2 hours') WHERE "periodEnd" IS NOT NULL AND EXTRACT(HOUR FROM "periodEnd") IN (22, 23) AND EXTRACT(MINUTE FROM "periodEnd") = 0 AND EXTRACT(SECOND FROM "periodEnd") = 0;
UPDATE "TaxPayment" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "TaxPayment" SET "paymentDate" = date_trunc('day', "paymentDate" + interval '2 hours') WHERE "paymentDate" IS NOT NULL AND EXTRACT(HOUR FROM "paymentDate") IN (22, 23) AND EXTRACT(MINUTE FROM "paymentDate") = 0 AND EXTRACT(SECOND FROM "paymentDate") = 0;
UPDATE "StatusReport" SET "reportDate" = date_trunc('day', "reportDate" + interval '2 hours') WHERE "reportDate" IS NOT NULL AND EXTRACT(HOUR FROM "reportDate") IN (22, 23) AND EXTRACT(MINUTE FROM "reportDate") = 0 AND EXTRACT(SECOND FROM "reportDate") = 0;
UPDATE "StatusReport" SET "periodStart" = date_trunc('day', "periodStart" + interval '2 hours') WHERE "periodStart" IS NOT NULL AND EXTRACT(HOUR FROM "periodStart") IN (22, 23) AND EXTRACT(MINUTE FROM "periodStart") = 0 AND EXTRACT(SECOND FROM "periodStart") = 0;
UPDATE "StatusReport" SET "periodEnd" = date_trunc('day', "periodEnd" + interval '2 hours') WHERE "periodEnd" IS NOT NULL AND EXTRACT(HOUR FROM "periodEnd") IN (22, 23) AND EXTRACT(MINUTE FROM "periodEnd") = 0 AND EXTRACT(SECOND FROM "periodEnd") = 0;
UPDATE "StatusReportAction" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "RaidItem" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "MeetingMinutes" SET "date" = date_trunc('day', "date" + interval '2 hours') WHERE "date" IS NOT NULL AND EXTRACT(HOUR FROM "date") IN (22, 23) AND EXTRACT(MINUTE FROM "date") = 0 AND EXTRACT(SECOND FROM "date") = 0;
UPDATE "MeetingActionItem" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "PlanTask" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "PlanTask" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "CutoverTask" SET "startDate" = date_trunc('day', "startDate" + interval '2 hours') WHERE "startDate" IS NOT NULL AND EXTRACT(HOUR FROM "startDate") IN (22, 23) AND EXTRACT(MINUTE FROM "startDate") = 0 AND EXTRACT(SECOND FROM "startDate") = 0;
UPDATE "CutoverTask" SET "endDate" = date_trunc('day', "endDate" + interval '2 hours') WHERE "endDate" IS NOT NULL AND EXTRACT(HOUR FROM "endDate") IN (22, 23) AND EXTRACT(MINUTE FROM "endDate") = 0 AND EXTRACT(SECOND FROM "endDate") = 0;
UPDATE "UatTestCase" SET "dateRun" = date_trunc('day', "dateRun" + interval '2 hours') WHERE "dateRun" IS NOT NULL AND EXTRACT(HOUR FROM "dateRun") IN (22, 23) AND EXTRACT(MINUTE FROM "dateRun") = 0 AND EXTRACT(SECOND FROM "dateRun") = 0;
UPDATE "UatIssue" SET "dateRaised" = date_trunc('day', "dateRaised" + interval '2 hours') WHERE "dateRaised" IS NOT NULL AND EXTRACT(HOUR FROM "dateRaised") IN (22, 23) AND EXTRACT(MINUTE FROM "dateRaised") = 0 AND EXTRACT(SECOND FROM "dateRaised") = 0;
UPDATE "UatIssue" SET "dateClosed" = date_trunc('day', "dateClosed" + interval '2 hours') WHERE "dateClosed" IS NOT NULL AND EXTRACT(HOUR FROM "dateClosed") IN (22, 23) AND EXTRACT(MINUTE FROM "dateClosed") = 0 AND EXTRACT(SECOND FROM "dateClosed") = 0;
UPDATE "Ticket" SET "dueDate" = date_trunc('day', "dueDate" + interval '2 hours') WHERE "dueDate" IS NOT NULL AND EXTRACT(HOUR FROM "dueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "dueDate") = 0 AND EXTRACT(SECOND FROM "dueDate") = 0;
UPDATE "TicketWorklog" SET "workedOn" = date_trunc('day', "workedOn" + interval '2 hours') WHERE "workedOn" IS NOT NULL AND EXTRACT(HOUR FROM "workedOn") IN (22, 23) AND EXTRACT(MINUTE FROM "workedOn") = 0 AND EXTRACT(SECOND FROM "workedOn") = 0;
UPDATE "UatScript" SET "sentAt" = date_trunc('day', "sentAt" + interval '2 hours') WHERE "sentAt" IS NOT NULL AND EXTRACT(HOUR FROM "sentAt") IN (22, 23) AND EXTRACT(MINUTE FROM "sentAt") = 0 AND EXTRACT(SECOND FROM "sentAt") = 0;
UPDATE "Invoice" SET "issueDate" = date_trunc('day', "issueDate" + interval '2 hours') WHERE "issueDate" IS NOT NULL AND EXTRACT(HOUR FROM "issueDate") IN (22, 23) AND EXTRACT(MINUTE FROM "issueDate") = 0 AND EXTRACT(SECOND FROM "issueDate") = 0;
